### ISSUE TITLE
Replace mysql connector package in preparation of ansible mysql modules 4.x

### ISSUE THREAD

**Issue by raypappa** [xolyu/ansible-role-mariadb#1]
Ansible is deprecating use of this client, the new package would be `python3-pymysql`
https://github.com/xolyu/ansible-role-mariadb/blob/c2433c18d86cbf276d5de43f1d71613572eb4305/tasks/10_setup-Debian.yml#L5

I see this in my playbook runs
```
Warning: : Support of mysqlcline/MySQLdb connector is deprecated. We'll stop
testing against it in collection version 4.0.0 and remove the related code in
5.0.0. Use PyMySQL connector instead.
```

https://github.com/ansible-collections/community.mysql/issues/654
https://github.com/ansible-collections/community.mysql/issues/646

Given that 3.x has been out since 2021, I would say that 4.x is probably going to be soon-ish.

**Comment by xolyu** [comment]
Thank you for this information.  
I have replaced the requirement.
